chore: Implement Coverage Comparison Between Feature Branch Against Main Branch
Resolves: PQE-407

diff --git a/.github/workflows/go-test.yml b/.github/workflows/go-test.yml
--- a/.github/workflows/go-test.yml
+++ b/.github/workflows/go-test.yml
@@ -26,29 +26,14 @@ on:
       - "synchronize"
 
 jobs:
-
-  # TODO: fix existing issues before uncommenting
-  # vet:
-  #   name: Vet source code
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout source code for this repository
-  #       uses: actions/checkout@v4
-  #
-  #     - name: Install Go
-  #       uses: actions/setup-go@v5
-  #       with:
-  #         go-version-file: go.mod
-  #         cache: true
-  #         check-latest: true
-  #
-  #     - name: Vet Code
-  #       run: |
-  #         go vet ./...
-
   test:
     runs-on: ubuntu-latest
+    needs: upload-main-coverage-file
     steps:
+      - env:
+          COV_FILE_ID: ${{ needs.upload-main-coverage-file.outputs.coverage-artifact-id }}
+        run: echo "Artifact ID from previous job is $COV_FILE_ID"
+
       - name: Checkout source code for this repository
         uses: actions/checkout@v4
 
@@ -61,8 +46,41 @@ jobs:
 
       - name: Run Tests
         run: |
-          go test ./...
+          make test
+     
+      - name: Parse Coverage Value From Feature Branch
+        run: |
+          echo "current_coverage=$(tail -n 1 .coverage/coverage.txt | awk '{print $3}' | awk 'sub("%", "")')" >> $GITHUB_ENV
+     
+      - name: Feature Branch Coverage Value
+        run: |
+          printf 'Coverage Value: %s\n' "$current_coverage"
+     
+      - name: Download Main Coverage
+        uses: actions/download-artifact@v8
+        with:
+          artifact-ids: ${{ needs.upload-main-coverage-file.outputs.coverage-artifact-id }}
+          path: tmp/
 
+      - name: Display structure of downloaded files
+        run: ls -R
+
+      - name: Parse Coverage Value From Main Branch
+        run: |
+          echo "main_coverage=$(tail -n 1 tmp/coverage.txt | awk '{print $3}' | awk 'sub("%", "")')" >> $GITHUB_ENV
+     
+      - name: Main Coverage Value
+        run: |
+          printf 'Coverage Value: %s\n' "$main_coverage"
+     
+      - name: Coverage Evaluation
+        run: |
+          if (( echo "$current_coverage < $main_coverage" | bc -l)); then
+            echo "Failing the workflow. Coverage on feature branch ($current_coverage%) is below main branch ($main_coverage%)"
+            exit 1
+          else
+            echo "Coverage is within the limits"
+          fi
   integration-test-pg:
     name: Run integration tests (pg)
     runs-on: ubuntu-latest
@@ -95,7 +113,7 @@ jobs:
         env:
           CONNECTION_STRING: postgres://dawgs:weneedbetterpasswords@localhost:5432/dawgs?sslmode=disable
         run: |
-          go test -tags manual_integration ./integration 
+          make test_integration
 
   integration-test-neo4j:
     name: Run integration tests (neo4j)
@@ -128,4 +146,4 @@ jobs:
         env:
           CONNECTION_STRING: neo4j://neo4j:weneedbetterpasswords@localhost:7687
         run: |
-          go test -tags manual_integration ./integration 
+          make test_integration
